name: Build Docs and Deploy Generated Code

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_and_deploy:
        name: Build Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Packages
              run: npx -y pnpm i

            - name: TypeDoc Build
              run: npm run build && npm run docs
              env:
                  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

            - name: Deploy Docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./docs"
                  publish_branch: "gh-pages"

            - name: Deploy Generated TypeScript Code
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./src"
                  publish_branch: "fonts-ts"
